# This file is disabled to prevent duplicate workflow runs
# The active workflow is in azure-static-web-apps-icy-rock-07ac03510.yml

name: Azure Static Web Apps CI/CD (DISABLED)

# Removed all triggers to prevent this workflow from running
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened, closed]
#     branches:
#       - main

jobs:
  # All jobs have been commented out to prevent this workflow from running
  
  # build_and_deploy_job:
  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
  #   runs-on: ubuntu-latest
  #   name: Build and Deploy Job
  #   steps:
  #     ...
  
  # close_pull_request_job:
  #   if: github.event_name == 'pull_request' && github.event.action == 'closed'
  #   runs-on: ubuntu-latest
  #   name: Close Pull Request Job
  #   steps:
  #     ...
